<a href="https://colab.research.google.com/github/malavikasreekumar/creditcard_fraud/blob/master/Creditcard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
cd gdrive

/content/gdrive


In [0]:
cd My Drive

/content/gdrive/My Drive


In [0]:
cd creditcardfraud/

/content/gdrive/My Drive/creditcardfraud


In [0]:
import numpy as np
import pandas as pd

from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn import metrics
df=pd.read_csv('creditcard.csv')
X=df.iloc[:,0:30].values
y=df.iloc[:,30].values

In [0]:
y,X

(array([0, 0, 0, ..., 0, 0, 0]),
 array([[ 0.00000000e+00, -1.35980713e+00, -7.27811733e-02, ...,
          1.33558377e-01, -2.10530535e-02,  1.49620000e+02],
        [ 0.00000000e+00,  1.19185711e+00,  2.66150712e-01, ...,
         -8.98309914e-03,  1.47241692e-02,  2.69000000e+00],
        [ 1.00000000e+00, -1.35835406e+00, -1.34016307e+00, ...,
         -5.53527940e-02, -5.97518406e-02,  3.78660000e+02],
        ...,
        [ 1.72788000e+05,  1.91956501e+00, -3.01253846e-01, ...,
          4.45477214e-03, -2.65608286e-02,  6.78800000e+01],
        [ 1.72788000e+05, -2.40440050e-01,  5.30482513e-01, ...,
          1.08820735e-01,  1.04532821e-01,  1.00000000e+01],
        [ 1.72792000e+05, -5.33412522e-01, -1.89733337e-01, ...,
         -2.41530880e-03,  1.36489143e-02,  2.17000000e+02]]))

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [0]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.fit_transform(X_test)

# **Logistic Regression**

In [22]:
from sklearn.linear_model import LogisticRegression
lr_classifier=LogisticRegression()
lr_classifier.fit(X_train,y_train)

lr_pred=lr_classifier.predict(X_test)
lr_cm=confusion_matrix(y_test,lr_pred)

print("Accuracy=",metrics.accuracy_score(y_test,lr_pred))
print(lr_cm)

Accuracy= 0.9992135052386169
[[71078     9]
 [   47    68]]


## **KNN**

In [29]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier=KNeighborsClassifier(n_neighbors=3,metric='manhattan',p=2)
knn_classifier.fit(X_train, y_train)

knn_pred = knn_classifier.predict(X_test)
knn_cm = confusion_matrix(y_test, knn_pred)



print("Accuracy=",metrics.accuracy_score(y_test, knn_pred))

print(knn_cm)

Accuracy= 0.999592708069998
[[71082     5]
 [   24    91]]


## **Decision Tree**

In [25]:
from sklearn.tree import DecisionTreeClassifier
dtree_classifier=DecisionTreeClassifier()
dtree_classifier.fit(X_train,y_train)

dtree_pred=dtree_classifier.predict(X_test)
dtree_cm=confusion_matrix(y_test,dtree_pred)

print("Accuracy=",metrics.accuracy_score(y_test,dtree_pred))
print(dtree_cm)

Accuracy= 0.999115193393444
[[71052    35]
 [   28    87]]


## **Naive Bayes**

In [26]:
from sklearn.naive_bayes import GaussianNB
nb_classifier=GaussianNB()
nb_classifier.fit(X_train,y_train)

nb_pred =nb_classifier.predict(X_test)

nb_cm = confusion_matrix(y_test, nb_pred)

print("Accuracy=",metrics.accuracy_score(y_test, nb_pred))

print(nb_cm)

Accuracy= 0.9791578888233476
[[69623  1464]
 [   20    95]]


## **SVM**

In [28]:
from sklearn.svm import SVC
svc_classfier=SVC()
svc_classfier.fit(X_train,y_train)

svc_pred=svc_classfier.predict(X_test)
svc_cm=confusion_matrix(y_test,svc_pred)

print("Accuracy=",metrics.accuracy_score(y_test, svc_pred))
print(svc_cm)

Accuracy= 0.9993399061824106
[[71084     3]
 [   44    71]]
